FROM node:22

WORKDIR /app

COPY package*.json /.
RUN npm install

# RUN npm install next@canary # install next@canary again -- because of an error the version is reset after a normal "npm install"

COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
